<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>休暇形態</name>
   <tag></tag>
   <elementGuidId>1eb0259b-6814-481b-9fbf-580a6ebb42bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/main[1]/section[1]/section[2]/section[3]/section[1]/table[2]/tr[2]/td[2]/div[1]/div[1]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
