<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>打刻エラー</name>
   <tag></tag>
   <elementGuidId>94e77392-c17e-4e75-9c17-c0e1dc1537e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/main[1]/section[3]/section[1]/table[1]/tbody[1]/tr[2]/td[5]/p[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
