<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>打刻日</name>
   <tag></tag>
   <elementGuidId>b3d07774-73f9-405c-b440-313d8b896aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/main[1]/section[7]/table[1]/tbody[1]/tr[2]/td[3]/div[1]/div[1]/select[1]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
