<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID_Input</name>
   <tag></tag>
   <elementGuidId>9863821e-2f88-4fb3-8fd8-e1963f67c611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='presentation_id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='presentation_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
