<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_click</name>
   <tag></tag>
   <elementGuidId>fc65e98c-0f63-40eb-b047-9f0e0ae76d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='presentation_id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
