<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pass_Input</name>
   <tag></tag>
   <elementGuidId>8c1779de-6e7a-4e61-a1e1-ac379f4d5483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='presentation_id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
